### ISSUE TITLE
[SALARY_COMPETITION](Alvaro Lorenzo)

### ISSUE THREAD

**Issue by alorenzoti** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#11]
https://github.com/alorenzoti/salarios_1

**Comment by fjgarciaes** [comment]
Un readme un poco escueto y una presentación inexistente jaja pero buen trabajo. En este ultimo feedback aprovecho para felicitarte por tu duro trabajo y tu constancia a lo largo del bootcamp, se que no es un camino fácil y a veces las cosas se complican pero has sabido llevarlo de una buena manera. Se que puedes dar mucho y estoy seguro que lo vas a demostrar con un excelente proyecto final así que a por todas :)
