### ISSUE TITLE
SALARY_COMPETITION (Axel)

### ISSUE THREAD

**Issue by AxelCrypto** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#14]
https://github.com/AxelCrypto/ML-Kaggle-Competition

**Comment by fjgarciaes** [comment]
Buen trabajo Axel pero intenta no meter codigo en el readme. Te felicito por tu trabajo a lo largo de estas semanas y por la actitud y el interés que has mostrado a lo largo del bootcamp preguntando siempre tus dudas y tus inquietudes que estoy seguro te habra ayudado mucho a mejorar en lo que querías. Mucho animo con el proyecto final, estoy seguro que sera un trabajado.
