### ISSUE TITLE
[SALARY_COMPETITION](Jorge Mendoza)

### ISSUE THREAD

**Issue by jmgpgit** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#15]
https://github.com/jmgpgit/Machine_Learning_Project

**Comment by fjgarciaes** [comment]
Aprovecho este ultimo feedback para felicitarte por el trabajo y el esfuerzo durante todo el bootcamp aunque me hubiera gustado ver un poco de esfuerzo en este ultimo proyecto, sigue esforzándote y animo con el proyecto final.
