### ISSUE TITLE
[SALARY_COMPETITION](Jorge Freire)

### ISSUE THREAD

**Issue by jorgefreires** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#17]
https://github.com/jorgefreires/Predict-the-Salary-for-Data-Science-Jobs

**Comment by fjgarciaes** [comment]
Muy buen trabajo Jorge y tanto el readme como la presentación esta bien. Te felicito por tu gran trabajo y evolución durante todo el bootcamp, te has esforzado al máximo en los labs y los proyectos y siempre has estado dispuesta a ayudar a tus compañeros cuando lo necesitaban lo cual es muy importante en este proceso. Te animo a seguir así y a darlo todo en el proyecto final.
