### ISSUE TITLE
[Competencia](Lohengrin Verde)

### ISSUE THREAD

**Issue by lohe040789** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#2]
https://github.com/lohe040789/Competencia_Salarios

**Comment by fjgarciaes** [comment]
Buen trabajo Lohe aunque intenta que lo primero del readme no sea una imagen porque si alguien no tiene el contexto igual no lo entiende. Por otro lado como este es el ultimo feedback aprovecho para felicitarte por tu excelente actitud durante el bootcamp así como por tu esfuerzo en los labs y proyectos ya que se ha visto una gran evolución. Animo y a por todas con el proyecto final.
