### ISSUE TITLE
[Salary competition](Manuel Zerpa)

### ISSUE THREAD

**Issue by Manuelzerpadl** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#22]
https://github.com/Manuelzerpadl/SALARY_COMPETITION.git

**Comment by fjgarciaes** [comment]
Muy buen proyecto y la presentación aunque el readme un poco corto jaja. Como este es el ultimo feedback aprovecho ara felicitarte por tu trabajo durante el bootcamp he podido ver como has ido aprendiendo y mejorando con el paso de los días y has sacado provecho a las clases, ademas has mantenido una muy buena actitud en todo momento, cosa que no es fácil durante todo este proceso, así que te animo a que sigas así de cara al proyecto final que estoy seguro va a ser un gran trabajo.
