### ISSUE TITLE
{'Salary Competition': 'Carlos Mato'}

### ISSUE THREAD

**Issue by CharlyKill7** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#23]
https://github.com/CharlyKill7/Salary-Machine-Learning

**Comment by fjgarciaes** [comment]
Muy bien el proyecto Carlos, aunque intenta no meter codigo dentro del readme. Quería aprovechar el ultimo feedback para felicitarte por tu gran evolución dentro del bootcamp, se ha notado una gran mejoría a lo largo de las semanas, he visto tu esfuerzo, tus ganas de aprender y entender lo que hacías y esa actitud ha sido la que te ha llevado hasta donde estas ahora, realizando un proyecto complicado que se de sobra que puedes sacar así que te animo con ello que se que puedes con eso y mas :)
