### ISSUE TITLE
[SALARY_COMPETITION](Paula García)

### ISSUE THREAD

**Issue by pgmar257** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#26]
https://github.com/pgmar257/Kaggle-Project

**Comment by fjgarciaes** [comment]
Bien Paula, el readme me ha gustado. Aprovecho este ultimo feedback antes del proyecto final para felicitarte por tu progreso durante el bootcamp ya que a pesar de que has tenido momentos difíciles o algunos labs que se te han podido complicar mas has seguido adelante y no te has dado por vencida así que enhorabuena por ello, estoy seguro que puedes y vas a sacar un buen proyecto final que estoy deseando ver así que mucho animo y a tope con las motos!!
