### ISSUE TITLE
[ SALARY_COMPETITION ] (PedroVidales)

### ISSUE THREAD

**Issue by PedroVidales** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#27]
https://github.com/PedroVidales/SALARY_COMPETITION_MAIN

**Comment by fjgarciaes** [comment]
Pedro echale un ojo al readme de tu repo porque has subido otro tipo de archivo y no se ve, la presentación esta bien aunque intenta no meter mucho texto. Como este es el ultimo feedback aprovecho para felicitarte por tu progreso y tu evolución a lo largo de estas semanas, has tenido una buena actitud y creo que has aprovechado y aprendido dentro del bootcamp así que demuestra todo lo que sabes con el proyecto final, a por todas !!
