### ISSUE TITLE
[SALARY_COMPETITION](Paula_Alvarez)

### ISSUE THREAD

**Issue by paulaalvarezsa** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#28]
https://github.com/paulaalvarezsa/8.Salary_competition/blob/main/README.md

**Comment by fjgarciaes** [comment]
Paula intenta hacer un readme y si en el futuro tienes tiempo darle una vuelta a este proyecto, ya que es bastante interesante. Aprovecho este ultimo feedback para felicitarte por tu evolución durante estas semanas y por haber superado todas las trabas que te ha podido poner el bootcamp durante este tiempo, se que no ha sido facil pero poco a poco y con constancia has llegado hasta aquí así que te animo a demostrar todo lo que has aprendido en el proyecto final que seguro  va a ir fenomenal :)

**Comment by paulaalvarezsa** [comment]
Muchas gracias!! 💕💕
