### ISSUE TITLE
[SALARY-COMPETITION](Paula Bendito Buhles)

### ISSUE THREAD

**Issue by paulabnbh** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#3]
https://github.com/paulabnbh/Kaggle-completition-project

**Comment by fjgarciaes** [comment]
Buen trabajo Paula y enhorabuena por haber sido la ganadora de la competición, recuerda meter en carpetas los archivos y el readme hacerlo un poco mas vistoso. En este ultimo feedback quiero felicitarte por todo lo que has conseguido durante estas semanas, has trabajado muy duro y te has esforzado mucho lo cual se ha notado y se ha visto dia tras día, hemos podido ver tu gran evolución proyecto tras proyecto, los cuales siempre has conseguido sacar de una manera muy solvente y buena, ademas destacar tu actitud sobretodo con nosotros que ha hecho que puedes seguir avanzando. Se que tu proyecto final sera increíble así que mucho animo con ello.
