### ISSUE TITLE
[SALARY_COMPETITION](Ronald Hernandez)

### ISSUE THREAD

**Issue by Ronher1992** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#31]
https://github.com/Ronher1992/Project_Salary_Competition-.git

**Comment by fjgarciaes** [comment]
Ronald me habría gustado ver un readme y una presentación ya que se trataba del ultimo proyecto así que si en algún momento tienes un rato intenta hacerlo ya que es interesante de cara a si alguien entra a tu GitHub lo vea. Aprovecho este ultimo feedback para felicitarte por tu trabajo y la evolución que has tenido a lo largo de todo el bootcamp, estoy seguro que vas a poder demostrar todo lo que has aprendido en el proyecto final así que animo y a por ello!!
