### ISSUE TITLE
[SALARY_COMPETITION](Alfonso Urra)

### ISSUE THREAD

**Issue by AlfonsoUrra** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#35]
https://github.com/AlfonsoUrra/Salary-Competition.git

**Comment by fjgarciaes** [comment]
Buen trabajo Alfonso aunque intenta no meter codigo en el readme y me hubiese gustado ver una presentación. Aprovecho este ultimo feedback para felicitarte por el trabajo que has realizado a lo largo de todo el bootcamp, lo has aprovechado y se nota la evolución con el paso de las semanas. Ademas quería agradecerte que escucharas nuestros consejos y te aplicases a no llegar tarde jaja es algo a tener en cuenta. Te animo a trabajar duro en el proyecto final que estoy seguro va a ser un gran trabajo.
