### ISSUE TITLE
SALARY_COMPETITION(jel)

### ISSUE THREAD

**Issue by jel-garay** [Ironhack-Data-Madrid-Enero-2023/SALARY_COMPETITION#7]
https://github.com/jel-garay/SALARY_COMPETITION.git

**Comment by fjgarciaes** [comment]
Buen trabajo Jel, aunque intenta no meter tanto texto en la presentación y el readme hacerlo un poco mas visual. Aprovecho este ultimo feedback para felicitarte por tu evolución a lo largo de estas semanas y por tu actitud, creo que has sabido aprovechar el bootcamp y te animo a que demuestres todo lo que has aprendido en el proyecto final!!
